[profile.default]
auto_detect_solc = true
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@OZ/=lib/openzeppelin-contracts/contracts/",
    "@forge/=lib/forge-std/",
    "@devops/=lib/foundry-devops/"
]
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
    { access = "read", path = "./images/"},
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
